quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc=false
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5433/inventory_db
quarkus.datasource.username=inventory
quarkus.datasource.password=admin4321
quarkus.datasource.devservices.enabled=true

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
